LOAD DATA LOCAL INFILE 'item.dat' INTO TABLE Item
FIELDS TERMINATED BY '|*|';

LOAD DATA LOCAL INFILE 'bidder.dat' INTO TABLE Bidder
FIELDS TERMINATED BY '|*|';

LOAD DATA LOCAL INFILE 'bid.dat' INTO TABLE Bid
FIELDS TERMINATED BY '|*|';

LOAD DATA LOCAL INFILE 'seller.dat' INTO TABLE Seller
FIELDS TERMINATED BY '|*|';

LOAD DATA LOCAL INFILE 'category.dat' INTO TABLE Category
FIELDS TERMINATED BY '|*|';